# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    resolvers:
        default:
            web_path: ~

    filter_sets:
        cache: ~

        cardThumb:
            quality: 100
            # list of transformations to apply (the "filters")
            filters:
                thumbnail: { size: [300, 150], mode: outbound }

        w1920:
            quality: 100
            # list of transformations to apply (the "filters")
            filters:
                relative_resize:
                    widen: 1920

        startPageProfile:
            quality: 100
            # list of transformations to apply (the "filters")
            filters:
                relative_resize:
                    widen: 250


        x050:
            quality: 100
            # list of transformations to apply (the "filters")
            filters:
                downscale:
                    by: 0.5

        x025:
            quality: 100
            # list of transformations to apply (the "filters")
            filters:
                downscale:
                    by: 0.25

        x075:
            quality: 100
            # list of transformations to apply (the "filters")
            filters:
                downscale:
                    by: 0.75

        x100:
            quality: 100
