FORMAT: 1A
HOST: https://kevink.dev/api/

# KevinK.dev Public API

The KevinK.dev Public API allows anyone to pull data from KevinK.dev without any need to pay or register.

## Blogging Module [/blog]

### Get Newest Post [GET/blog/{locale}/newest]

Get the newest post in your preferred locale. If that locale is not available the system will fallback to english.

+ Parameters
    + locale: `en` (string) - Any supported locale.

+ Response 200 (application/json)

        {
          "id": 1,
          "title": "Hello World!",
          "summary": "Hello Wold, this is Kevin and this is my site.\n",
          "content": "echo \"Hello World!\";\n\n\n<p>Hello World, this is Kevin. As you might have guessed from the domain of this site I am the owner. This site is my personal platform for everything I want to put out there like blog posts, projects and photos. Right now the site is under development, so there are some modules which are not enabled yet.</p>\n",
          "image": "https://kevink.dev/assets/images/mario-caruso-770233-unsplash.jpg",
          "publishTime": "1555598400",
          "formattedTime": "18.04.2019",
          "author": {
            "id": 1,
            "publicName": "Kevin Kandlbinder"
          },
          "category": {
            "id": 1,
            "name": "General"
          }
        }

### Get Post By ID [GET/blog/{locale}/{id}]

Get a specific post in your preferred locale. If that locale is not available the system will fallback to english.

+ Parameters
    + locale: `en` (string) - Any supported locale.
    + id: 1 (number) - ID of a specific post.
    
+ Response 200 (application/json)
        
        {
          "id": 1,
          "title": "Hello World!",
          "summary": "Hello Wold, this is Kevin and this is my site.\n",
          "content": "echo \"Hello World!\";\n\n\n<p>Hello World, this is Kevin. As you might have guessed from the domain of this site I am the owner. This site is my personal platform for everything I want to put out there like blog posts, projects and photos. Right now the site is under development, so there are some modules which are not enabled yet.</p>\n",
          "image": "https://kevink.dev/assets/images/mario-caruso-770233-unsplash.jpg",
          "publishTime": "1555598400",
          "formattedTime": "18.04.2019",
          "author": {
            "id": 1,
            "publicName": "Kevin Kandlbinder"
          },
          "category": {
            "id": 1,
            "name": "General"
          }
        }